packageExtensions:
  # "@typescript-eslint/typescript-estree@*":
  #   dependencies:
  #     typescript: "*"
  # "eslint-config-airbnb-typescript@*":
  #   peerDependencies:
  #     eslint: "*"
  #     typescript: "*"
